services:
  - type: web
    name: syncsure-backend-v9
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_SSL
        value: true
      - key: PGSSLMODE
        value: require
